#!/usr/bin/env python3
"""
Historical replay validation — compare arena results to real journal data.

Loads a historical day from journals + bar cache, runs the arena exchange,
and compares: Were the same tickers evaluated? Did fills happen at
reasonable prices? What would P&L have been?

Usage:
    python mx-arena/scripts/prep_historical.py --date 2026-03-26
    python mx-arena/scripts/run_historical_validation.py --date 2026-03-26
"""

from __future__ import annotations

import argparse
import asyncio
import glob
import json
import logging
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from arena.clock import ClockMode, SimClock
from arena.data_engine import DataEngine
from arena.exchange import SimExchange
from arena.fill_model import AlpacaFillModel, Bar
from arena.harness import ArenaConfig, ArenaInstance
from arena.spread_model import SpreadModel

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)-5s %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
DATA_DIR = PROJECT_ROOT / "data"
ARENA_DATA = PROJECT_ROOT / "mx-arena" / "data"


def load_replay_config(date: str) -> dict:
    """Load replay config generated by prep_historical.py."""
    config_file = ARENA_DATA / "configs" / f"replay_{date}.json"
    if not config_file.exists():
        print(f"Error: No replay config for {date}. Run prep_historical.py first.")
        sys.exit(1)
    with open(config_file) as f:
        return json.load(f)


def load_journal_entries(date: str) -> list[dict]:
    """Load all journal entries for a date."""
    entries = []
    for f in glob.glob(str(DATA_DIR / "journals" / f"journal_{date}_*.jsonl")):
        with open(f) as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    entries.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    return entries


async def run_validation(date: str, verbose: bool = False):
    """Run historical replay and compare to journal data."""

    print(f"\n{'='*70}")
    print(f"HISTORICAL REPLAY VALIDATION: {date}")
    print(f"{'='*70}\n")

    # Load config
    config = load_replay_config(date)
    tickers = config["tickers"]
    prev_daily = config.get("prev_daily", {})
    journal_stats = config.get("journal_stats", {})

    # Load journal entries
    entries = load_journal_entries(date)
    buy_entries = [e for e in entries if e.get("action") in ("BUY", "STRONG_BUY")]
    no_trade_entries = [e for e in entries if e.get("action") == "NO_TRADE"]

    print(f"Journal: {len(entries)} entries, {len(buy_entries)} BUY, {len(no_trade_entries)} NO_TRADE")
    print(f"Tickers: {', '.join(tickers)}")

    # Create arena instance
    arena_config = ArenaConfig(
        date=date,
        symbols=tickers,
        data_dir=str(ARENA_DATA / "historical"),
        initial_cash=100_000.0,
        seed=42,
        prev_daily_bars=prev_daily,
    )

    instance = ArenaInstance(arena_config)

    # Override data engine to also search JSON bar cache
    instance.data_engine.json_bars_dir = DATA_DIR / "bars"

    # Load data
    instance.load_data()
    loaded_symbols = list(instance.data_engine._minute_bars.keys())

    print(f"\nLoaded bar data: {len(loaded_symbols)}/{len(tickers)} tickers")
    if loaded_symbols:
        print(f"  Available: {', '.join(loaded_symbols)}")
    missing = [t for t in tickers if t not in loaded_symbols]
    if missing:
        print(f"  Missing:   {', '.join(missing)}")

    # Run simulation (standalone — just drives exchange through bars)
    result = await instance.run_standalone()

    # -- Validation Report ----------------------------------------

    print(f"\n{'-'*70}")
    print("ARENA EXCHANGE RESULTS")
    print(f"{'-'*70}")
    print(f"  Clock ticks:  {instance.clock.tick_count}")
    print(f"  Orders:       {result.orders_total}")
    print(f"  Trades:       {len(result.trades)}")
    print(f"  P&L:          ${result.pnl:+.2f}")
    print(f"  Positions EOD: {len(result.positions_eod)}")

    # -- Compare to Journal ---------------------------------------

    print(f"\n{'-'*70}")
    print("JOURNAL vs ARENA COMPARISON")
    print(f"{'-'*70}")

    # Which buy tickers had bar data?
    buy_tickers = set(e.get("ticker") for e in buy_entries)
    buy_with_data = buy_tickers & set(loaded_symbols)
    buy_without_data = buy_tickers - set(loaded_symbols)

    print(f"\n  BUY signals in journal: {len(buy_entries)} across {len(buy_tickers)} tickers")
    print(f"  BUY tickers with bar data: {len(buy_with_data)}")
    if buy_without_data:
        print(f"  BUY tickers WITHOUT data: {', '.join(buy_without_data)}")

    # For each BUY ticker with bar data, check price reasonability
    if buy_with_data and verbose:
        print(f"\n  Entry Price Comparison:")
        for ticker in sorted(buy_with_data):
            ticker_buys = [e for e in buy_entries if e.get("ticker") == ticker]
            if not ticker_buys:
                continue

            journal_entry = ticker_buys[0]  # First BUY signal
            journal_price = journal_entry.get("entry_price", 0)
            journal_stop = journal_entry.get("stop_loss", 0)
            journal_gap = journal_entry.get("gap_pct", 0)

            # Arena bar data for this ticker
            bars = instance.data_engine._minute_bars.get(ticker, {})
            if bars:
                first_bar = bars.get(0)
                bar_open = first_bar.open if first_bar else 0
                bar_high = max(b.high for b in bars.values())
                bar_low = min(b.low for b in bars.values())
                bar_close = bars[max(bars.keys())].close

                print(f"\n    {ticker}:")
                print(f"      Journal: entry=${journal_price:.2f}, stop=${journal_stop:.2f}, "
                      f"gap={journal_gap:.1%}")
                print(f"      Arena:   open=${bar_open:.2f}, high=${bar_high:.2f}, "
                      f"low=${bar_low:.2f}, close=${bar_close:.2f}")

                # Would the stop have been hit?
                if journal_stop > 0 and bar_low <= journal_stop:
                    print(f"      ==> STOP HIT at ${bar_low:.2f} (stop=${journal_stop:.2f})")
                else:
                    # What would max gain have been?
                    if journal_price > 0:
                        max_gain_pct = (bar_high - journal_price) / journal_price
                        eod_return = (bar_close - journal_price) / journal_price
                        print(f"      ==> Max gain: {max_gain_pct:+.1%}, "
                              f"EOD return: {eod_return:+.1%}")

    # -- Price Coverage Summary -----------------------------------

    print(f"\n{'-'*70}")
    print("DATA COVERAGE")
    print(f"{'-'*70}")

    for ticker in sorted(loaded_symbols)[:10]:
        bars = instance.data_engine._minute_bars.get(ticker, {})
        if bars:
            n_bars = len(bars)
            first = bars[0]
            last = bars[max(bars.keys())]
            day_return = (last.close - first.open) / first.open if first.open > 0 else 0
            total_vol = sum(b.volume for b in bars.values())
            print(f"  {ticker:6s}: {n_bars:4d} bars, "
                  f"open=${first.open:7.2f} -> close=${last.close:7.2f} "
                  f"({day_return:+.1%}), vol={total_vol:>10,}")

    # -- Save validation report -----------------------------------

    report = {
        "date": date,
        "journal_entries": len(entries),
        "journal_buys": len(buy_entries),
        "journal_no_trades": len(no_trade_entries),
        "tickers_total": len(tickers),
        "tickers_with_data": len(loaded_symbols),
        "tickers_missing": missing,
        "arena_ticks": instance.clock.tick_count,
        "arena_orders": result.orders_total,
        "arena_trades": len(result.trades),
        "arena_pnl": result.pnl,
        "result": result.to_dict(),
    }

    out_dir = ARENA_DATA / "results"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"validation_{date}.json"
    with open(out_file, "w") as f:
        json.dump(report, f, indent=2, default=str)

    print(f"\nReport saved to {out_file}")
    print(f"{'='*70}\n")


async def main():
    parser = argparse.ArgumentParser(description="Historical replay validation")
    parser.add_argument("--date", type=str, required=True, help="Date to validate")
    parser.add_argument("-v", "--verbose", action="store_true", help="Show per-ticker details")
    args = parser.parse_args()
    await run_validation(args.date, verbose=args.verbose)


if __name__ == "__main__":
    asyncio.run(main())
