"""Phase A: out-of-sample threshold validation for MoMTrans tier cascade.

The session 128 result ($+91,629 vs production $+13,096 = +$78,533 lift)
was generated by grid-searching 600 threshold combos against the SAME
WF predictions used for evaluation. That's classic threshold-overfit
risk. This script validates whether the lift survives a strict
out-of-sample split:

    TUNE set:   folds 0-7  (oldest 8 folds, ~6,477 rows)
    VERIFY set: folds 8-15 (newest 8 folds, ~5,715 rows)

Procedure:
  1. Run threshold grid search on TUNE set alone -> best (E, H, V, B)
  2. Apply those frozen thresholds to VERIFY set
  3. Compare cascade $-PNL on VERIFY vs production v3 $-PNL on VERIFY
  4. Verdict: SHIP if VERIFY lift >= +$15k; HOLD if collapse to <+$5k

This is the standard "did the optimizer overfit?" test from financial
backtesting. If the session 128 result holds, the cascade is real.
If it collapses, threshold-overfit was the culprit.
"""
from __future__ import annotations
import json
from itertools import product
from pathlib import Path

import duckdb
import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[1]
DERIVED = REPO / "data" / "polygon_warehouse" / "derived"
MODELS = REPO / "data" / "models"

KELLY_CAPS = {"ELITE": 0.50, "HIGH": 0.35, "VETOED": 0.20, "BROAD": 0.10}
TIER_EW_EL_PCT = {
    "ELITE":  (0.7207, -0.0833),
    "HIGH":   (0.4075, -0.1745),
    "VETOED": (0.3490, -0.1421),
    "BROAD":  (0.3095, -0.1763),
}
BANKROLL = 10_000.0
TUNE_FOLDS = list(range(0, 8))      # folds 0-7 inclusive
VERIFY_FOLDS = list(range(8, 16))   # folds 8-15 inclusive


def section(t: str) -> None:
    print(f"\n{'='*72}\n{t}\n{'='*72}")


def kelly(p, w, ew, el, cap):
    if p < 0.30 or abs(el) < 1e-6 or ew <= 0:
        return 0.0
    b = abs(ew / el)
    q = 1.0 - p
    f_star = max(0.0, (b * p - q) / b)
    return float(min(f_star * float(np.exp(-2 * w)), cap))


def evaluate_momtrans_cascade(base: pd.DataFrame, thresholds: dict) -> dict:
    """MoMTrans tier cascade $-PNL with given per-tier thresholds.

    Cascade order (mutually exclusive): ELITE > HIGH > VETOED > BROAD.
    Tier fires when specialist >= threshold AND mag gate passes.
    """
    yreg = base["y_reg"].clip(-0.5, 1.0).values
    width = base["conformal_width"].values
    mag = base["mag_label"].values
    is_hi_mid = np.isin(mag, ["HI", "MID"])
    is_mid = mag == "MID"
    sp = {tier: base[f"prob_specialist_{tier}"].values
          for tier in ("ELITE", "HIGH", "VETOED", "BROAD")}

    elite = (sp["ELITE"] >= thresholds["ELITE"]) & is_hi_mid
    high = (sp["HIGH"] >= thresholds["HIGH"]) & is_hi_mid & ~elite
    vetoed = (sp["VETOED"] >= thresholds["VETOED"]) & is_mid & ~elite & ~high
    broad = (sp["BROAD"] >= thresholds["BROAD"]) & is_hi_mid & ~elite & ~high & ~vetoed

    out = {}
    total = 0.0
    for tier_name, mask, prob in [
        ("ELITE", elite, sp["ELITE"]),
        ("HIGH", high, sp["HIGH"]),
        ("VETOED", vetoed, sp["VETOED"]),
        ("BROAD", broad, sp["BROAD"]),
    ]:
        idx = np.where(mask)[0]
        if not len(idx):
            out[tier_name] = {"n": 0, "pnl": 0.0, "avg_pct": 0.0}
            continue
        ew, el = TIER_EW_EL_PCT[tier_name]; cap = KELLY_CAPS[tier_name]
        prob_eff = np.maximum(prob, 0.31)
        pnl = float(sum(BANKROLL * kelly(prob_eff[i], width[i], ew, el, cap) * yreg[i]
                          for i in idx))
        total += pnl
        out[tier_name] = {
            "n": int(len(idx)), "pnl": pnl,
            "avg_pct": float(yreg[idx].mean() * 100),
            "win_pct": float((yreg[idx] > 0).mean() * 100),
        }
    out["TOTAL"] = {"pnl": total}
    return out


def evaluate_production_baseline(prod: pd.DataFrame) -> dict:
    """Single-model production tier waterfall on v3-tuned-16f."""
    yreg = prod["y_reg"].clip(-0.5, 1.0).values
    prob = prod["prob_continuer"].values
    width = prod["conformal_width"].values
    mag = prod["mag_label"].values
    is_hi_mid = np.isin(mag, ["HI", "MID"])
    is_mid = mag == "MID"

    elite = (prob >= 0.60) & is_hi_mid
    high = (prob >= 0.50) & (prob < 0.60) & is_hi_mid
    vetoed = (prob >= 0.30) & (prob < 0.50) & is_mid
    broad = (prob >= 0.30) & (prob < 0.50) & is_hi_mid & ~vetoed

    out = {}
    total = 0.0
    for tier_name, mask in [("ELITE", elite), ("HIGH", high),
                                ("VETOED", vetoed), ("BROAD", broad)]:
        idx = np.where(mask)[0]
        if not len(idx):
            out[tier_name] = {"n": 0, "pnl": 0.0, "avg_pct": 0.0}
            continue
        ew, el = TIER_EW_EL_PCT[tier_name]; cap = KELLY_CAPS[tier_name]
        pnl = float(sum(BANKROLL * kelly(prob[i], width[i], ew, el, cap) * yreg[i]
                          for i in idx))
        total += pnl
        out[tier_name] = {
            "n": int(len(idx)), "pnl": pnl,
            "avg_pct": float(yreg[idx].mean() * 100),
            "win_pct": float((yreg[idx] > 0).mean() * 100),
        }
    out["TOTAL"] = {"pnl": total}
    return out


def main() -> int:
    section("Phase A — out-of-sample threshold validation")

    # Load specialists, build joined frame
    base = pd.read_parquet(MODELS / "momtrans_v4_tier_BROAD_predictions.parquet")[
        ["d0", "ticker", "fold", "y_reg", "prob_binary"]
    ].rename(columns={"prob_binary": "prob_specialist_BROAD"})
    base["d0"] = pd.to_datetime(base["d0"])
    for tier in ("VETOED", "HIGH", "ELITE"):
        df_t = pd.read_parquet(MODELS / f"momtrans_v4_tier_{tier}_predictions.parquet")[
            ["d0", "ticker", "fold", "prob_binary"]
        ]
        df_t["d0"] = pd.to_datetime(df_t["d0"])
        base = base.merge(
            df_t.rename(columns={"prob_binary": f"prob_specialist_{tier}"}),
            on=["d0", "ticker", "fold"], how="inner",
        )
    base["conformal_width"] = 0.5

    # Production baseline predictions
    prod = pd.read_parquet(DERIVED / "ml_v2_walkforward_predictions_v3_tuned_16fold.parquet")
    prod["d0"] = pd.to_datetime(prod["d0"])

    # Ising mag join
    ising_path = DERIVED / "ising_daily.parquet"
    con = duckdb.connect()
    con.sql(f"""CREATE TABLE i AS SELECT *,
        AVG(magnetization) OVER (ORDER BY d ROWS BETWEEN 4 PRECEDING AND CURRENT ROW)
        AS mag_5d FROM read_parquet('{ising_path.as_posix()}')""")
    mag_df = con.sql("""SELECT d AS d0,
        CASE WHEN mag_5d < -0.05 THEN 'LO' WHEN mag_5d > 0.05 THEN 'HI' ELSE 'MID' END
        AS mag_label FROM i""").df()
    mag_df["d0"] = pd.to_datetime(mag_df["d0"])
    base = base.merge(mag_df, on="d0", how="left").dropna(subset=["mag_label"])
    prod = prod.merge(mag_df, on="d0", how="left").dropna(subset=["mag_label"])

    # Split into TUNE (folds 0-7) and VERIFY (folds 8-15)
    base_tune = base[base["fold"].isin(TUNE_FOLDS)].reset_index(drop=True)
    base_verify = base[base["fold"].isin(VERIFY_FOLDS)].reset_index(drop=True)
    # Production has no `fold` column — split on date instead
    fold_dates = (base.groupby("fold")["d0"].agg(["min", "max"])).reset_index()
    tune_max_d0 = base_tune["d0"].max()
    verify_min_d0 = base_verify["d0"].min()
    prod_tune = prod[prod["d0"] <= tune_max_d0].reset_index(drop=True)
    prod_verify = prod[prod["d0"] >= verify_min_d0].reset_index(drop=True)

    print(f"  TUNE   set (folds 0-7):   MoMTrans={len(base_tune):,} rows  "
          f"prod={len(prod_tune):,} rows  date<={tune_max_d0.date()}")
    print(f"  VERIFY set (folds 8-15):  MoMTrans={len(base_verify):,} rows  "
          f"prod={len(prod_verify):,} rows  date>={verify_min_d0.date()}")

    section("Step 1 — Grid-search thresholds on TUNE set ONLY")
    elite_grid = [0.40, 0.50, 0.60, 0.70, 0.80, 0.90]
    high_grid = [0.40, 0.50, 0.60, 0.70, 0.80]
    vetoed_grid = [0.50, 0.60, 0.70, 0.80, 0.90]
    broad_grid = [0.50, 0.60, 0.70, 0.80]
    n_combos = len(elite_grid) * len(high_grid) * len(vetoed_grid) * len(broad_grid)
    print(f"  Searching {n_combos} threshold combos on TUNE set ({len(base_tune):,} rows)")

    best_tune_pnl = -1e18
    best_thresholds = None
    for e, h, v, b in product(elite_grid, high_grid, vetoed_grid, broad_grid):
        thr = {"ELITE": e, "HIGH": h, "VETOED": v, "BROAD": b}
        r = evaluate_momtrans_cascade(base_tune, thr)
        if r["TOTAL"]["pnl"] > best_tune_pnl:
            best_tune_pnl = r["TOTAL"]["pnl"]
            best_thresholds = thr

    tune_result = evaluate_momtrans_cascade(base_tune, best_thresholds)
    prod_tune_result = evaluate_production_baseline(prod_tune)
    print(f"\n  BEST thresholds (tuned on folds 0-7): {best_thresholds}")
    print(f"  TUNE-set MoMTrans cascade $-PNL: ${best_tune_pnl:+,.2f}")
    print(f"  TUNE-set production baseline $-PNL: ${prod_tune_result['TOTAL']['pnl']:+,.2f}")
    print(f"  TUNE-set lift: ${best_tune_pnl - prod_tune_result['TOTAL']['pnl']:+,.2f}")

    section("Step 2 — Apply FROZEN thresholds to VERIFY set")
    verify_result = evaluate_momtrans_cascade(base_verify, best_thresholds)
    prod_verify_result = evaluate_production_baseline(prod_verify)

    print(f"  VERIFY-set thresholds (FROZEN from TUNE): {best_thresholds}")
    print(f"\n  Per-tier comparison on VERIFY set:")
    print(f"  {'tier':<8} {'prod_n':>6} {'prod_$':>10} {'mt_n':>6} {'mt_$':>10} "
          f"{'delta_$':>10}")
    print("  " + "-" * 64)
    for tier in ("ELITE", "HIGH", "VETOED", "BROAD"):
        pn = prod_verify_result.get(tier, {}).get("n", 0)
        pp = prod_verify_result.get(tier, {}).get("pnl", 0.0)
        mn = verify_result[tier]["n"]
        mp = verify_result[tier]["pnl"]
        print(f"  {tier:<8} {pn:>6,} ${pp:>+9,.2f} {mn:>6,} ${mp:>+9,.2f} ${mp-pp:>+9,.2f}")
    verify_lift = verify_result["TOTAL"]["pnl"] - prod_verify_result["TOTAL"]["pnl"]
    print(f"  {'TOTAL':<8}        ${prod_verify_result['TOTAL']['pnl']:>+9,.2f} "
          f"       ${verify_result['TOTAL']['pnl']:>+9,.2f} ${verify_lift:>+9,.2f}")

    section("Step 3 — Verdict")
    print(f"  TUNE-set lift:   ${best_tune_pnl - prod_tune_result['TOTAL']['pnl']:+,.2f}")
    print(f"  VERIFY-set lift: ${verify_lift:+,.2f}")
    print(f"  Lift retention:  "
          f"{(verify_lift / max(best_tune_pnl - prod_tune_result['TOTAL']['pnl'], 1)) * 100:.1f}%")

    if verify_lift >= 15_000:
        verdict = "VALIDATED — cascade is real (VERIFY lift ≥ +$15k)"
    elif verify_lift >= 5_000:
        verdict = "WEAK_SIGNAL — some lift on VERIFY but reduced"
    elif verify_lift >= 0:
        verdict = "NEUTRAL — barely positive on VERIFY (some overfit)"
    elif verify_lift > -5_000:
        verdict = "MILD_OVERFIT — lift collapses to ~zero out-of-sample"
    else:
        verdict = "SEVERE_OVERFIT — cascade hurts on out-of-sample"
    print(f"  VERDICT: {verdict}")

    summary = {
        "tune_folds": TUNE_FOLDS,
        "verify_folds": VERIFY_FOLDS,
        "best_thresholds": best_thresholds,
        "tune_momtrans_pnl": best_tune_pnl,
        "tune_production_pnl": prod_tune_result["TOTAL"]["pnl"],
        "tune_lift": best_tune_pnl - prod_tune_result["TOTAL"]["pnl"],
        "verify_momtrans_pnl": verify_result["TOTAL"]["pnl"],
        "verify_production_pnl": prod_verify_result["TOTAL"]["pnl"],
        "verify_lift": verify_lift,
        "lift_retention_pct": (verify_lift / max(best_tune_pnl - prod_tune_result["TOTAL"]["pnl"], 1)) * 100,
        "verdict": verdict,
        "verify_per_tier_momtrans": verify_result,
        "verify_per_tier_production": prod_verify_result,
    }
    out = MODELS / "momtrans_v4_phase_a_oos_validation.json"
    out.write_text(json.dumps(summary, indent=2, default=str))
    print(f"\n  Wrote {out}")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
